apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: react-frontend
  name: react-frontend-service
  namespace: complains
  resourceVersion: "1835513"
  uid: a891c691-0e31-420d-aa66-d512c965a940
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.230.96
  clusterIPs:
  - 34.118.230.96
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31467
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: react-frontend
  sessionAffinity: None
  type: LoadBalancer
