apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  namespace: complains
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: react-frontend
  type: LoadBalancer
