pipeline:
  name: Build NewFastAPI
  identifier: Build_TautvydasGustas1_NewFastAPI_1710854377610
  projectIdentifier: Complains_Test
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: GCP_Connect
                    host: europe-west1-docker.pkg.dev
                    projectID: gcp-lbg-llm-poc
                    imageName: docker-repository/frontend
                    tags:
                      - frontend
                    dockerfile: Frontend/app/Dockerfile
                    context: Frontend/app
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: TautvydasGustas1/NewFastAPI
        build: <+input>
