apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
  namespace: complains
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    port: 8000
    targetPort: 8000
  selector:
    app: fastapi-backend
  sessionAffinity: None
  type: LoadBalancer
